-- Funções de negócio
-- Nota: Definições duplicadas/antigas foram removidas para evitar
-- sobrescrita da implementação real em database/functions/*.sql
-- e garantir que os gatilhos por evento funcionem corretamente.
